import Banner from "./../components/Home/Banner";
import Slogan from './../components/Home/Slogan';
export const metadata = {
  title: "Khalil Computer | Home",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div>
      <header>
        <Banner />
      </header>
      <section>
        <Slogan />
      </section>
    </div>
  );
}
