
import Banner from './../components/Home/Banner';
export const metadata = {
  title: "Khalil Computer | Home",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <header >
      <Banner></Banner>
    </header>
  );
}
